//! Tier-2 golden-fixture parity tests (ADR-0006).
//!
//! Each test loads a fixture from `tools/fixtures/` (generated by
//! `tools/gen_fixtures.py` running the upstream PyTorch modules verbatim),
//! runs the Burn port on the recorded input and asserts `max|Δ|` against the
//! recorded outputs stays within the fixture manifest's tolerance. Tests
//! skip with a message (instead of failing) when the fixture arrays/weights
//! are absent, since those are regenerated locally rather than committed.

use std::io::Read as _;
use std::path::{Path, PathBuf};

use burn::backend::NdArray;
use burn::tensor::{Tensor, TensorData};
use rvface_models::detector::SsdSlim320;
use rvface_models::embedder::{
    Irn50, MfnBottleneckConfig, MfnV2Config, MobileFaceNetEmbedder, MobileFaceNetV2Embedder,
};
use rvface_models::landmark::{MfnDwConfig, MobileFaceNetDw};
use rvface_models::pipnet::{PipnetConfig, PipnetLandmark};
use rvface_models::weights::{Arch, MfnArch, ModelManifest, Weights};

type B = NdArray;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn fixtures_dir() -> PathBuf {
    repo_root().join("tools/fixtures")
}

// ---------------------------------------------------------------------------
// Fixture manifest + npz/npy loading
// ---------------------------------------------------------------------------

#[derive(serde::Deserialize)]
struct FixtureManifest {
    fixture: String,
    /// Fixture-local safetensors name, or `real:<repo-relative path>`.
    weights: String,
    input_file: String,
    output_files: Vec<String>,
    tolerance: f64,
}

/// A float32 array read from an `.npz` member.
struct Array {
    shape: Vec<usize>,
    data: Vec<f32>,
}

/// Reads one `<member>` (sans `.npy` suffix) out of an `.npz` archive and
/// parses the trivial `.npy` v1/v2 header by hand (little-endian `<f4`,
/// C-order only — exactly what `gen_fixtures.py` writes).
fn npz_member(path: &Path, member: &str) -> Array {
    let file = std::fs::File::open(path).unwrap_or_else(|e| panic!("open {}: {e}", path.display()));
    let mut zip = zip::ZipArchive::new(file).expect("npz is a zip archive");
    let mut entry = zip
        .by_name(&format!("{member}.npy"))
        .unwrap_or_else(|e| panic!("npz member {member}.npy: {e}"));
    let mut buf = Vec::new();
    entry.read_to_end(&mut buf).expect("read npy member");
    parse_npy(&buf, member)
}

fn parse_npy(buf: &[u8], member: &str) -> Array {
    assert!(
        buf.len() > 10 && &buf[..6] == b"\x93NUMPY",
        "{member}: bad npy magic"
    );
    let (header_len, header_start) = match buf[6] {
        1 => (u16::from_le_bytes([buf[8], buf[9]]) as usize, 10),
        2 => (
            u32::from_le_bytes([buf[8], buf[9], buf[10], buf[11]]) as usize,
            12,
        ),
        v => panic!("{member}: unsupported npy version {v}"),
    };
    let header = std::str::from_utf8(&buf[header_start..header_start + header_len])
        .expect("npy header is ascii");
    assert!(
        header.contains("'descr': '<f4'"),
        "{member}: expected little-endian float32, header: {header}"
    );
    assert!(
        header.contains("'fortran_order': False"),
        "{member}: expected C order, header: {header}"
    );
    let shape_src = header
        .split("'shape': (")
        .nth(1)
        .and_then(|s| s.split(')').next())
        .unwrap_or_else(|| panic!("{member}: no shape in header: {header}"));
    let shape: Vec<usize> = shape_src
        .split(',')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(|s| s.parse().expect("shape dimension"))
        .collect();
    let payload = &buf[header_start + header_len..];
    let expected: usize = shape.iter().product();
    assert_eq!(
        payload.len(),
        expected * 4,
        "{member}: payload size mismatch"
    );
    let data = payload
        .chunks_exact(4)
        .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
        .collect();
    Array { shape, data }
}

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

/// Loaded fixture: manifest + resolved file paths, or `None` (skip).
struct Fixture {
    manifest: FixtureManifest,
    npz: PathBuf,
    weight_bytes: Vec<u8>,
}

/// Loads a fixture by name, returning `None` (with an explanation on
/// stderr) when any required file is absent.
fn load_fixture(name: &str) -> Option<Fixture> {
    let dir = fixtures_dir();
    let manifest_path = dir.join(format!("{name}.json"));
    let Ok(json) = std::fs::read_to_string(&manifest_path) else {
        eprintln!(
            "skipping {name}: fixture manifest {} absent",
            manifest_path.display()
        );
        return None;
    };
    let manifest: FixtureManifest = serde_json::from_str(&json).expect("fixture manifest parses");
    assert_eq!(manifest.fixture, name);

    let npz = dir.join(format!("{name}.npz"));
    if !npz.exists() {
        eprintln!("skipping {name}: fixture data {} absent", npz.display());
        return None;
    }

    let weights_path = match manifest.weights.strip_prefix("real:") {
        Some(repo_relative) => repo_root().join(repo_relative),
        None => dir.join(&manifest.weights),
    };
    let Ok(weight_bytes) = std::fs::read(&weights_path) else {
        eprintln!("skipping {name}: weights {} absent", weights_path.display());
        return None;
    };

    Some(Fixture {
        manifest,
        npz,
        weight_bytes,
    })
}

impl Fixture {
    fn weights(&self) -> Weights<B> {
        Weights::from_safetensors(&self.weight_bytes, &Default::default())
            .expect("fixture weights parse")
    }

    fn input(&self) -> Tensor<B, 4> {
        let member = member_name(&self.manifest.input_file);
        let arr = npz_member(&self.npz, member);
        assert_eq!(arr.shape.len(), 4, "input must be NCHW");
        let shape = [arr.shape[0], arr.shape[1], arr.shape[2], arr.shape[3]];
        Tensor::from_data(TensorData::new(arr.data, shape), &Default::default())
    }

    fn output(&self, member: &str) -> Array {
        assert!(
            self.manifest
                .output_files
                .iter()
                .any(|f| member_name(f) == member),
            "fixture {} has no output member {member}",
            self.manifest.fixture
        );
        npz_member(&self.npz, member)
    }

    /// Asserts `max|Δ|` between `got` and the recorded `member` is within the
    /// manifest tolerance, and reports the observed value.
    fn check(&self, member: &str, got: &[f32]) {
        let want = self.output(member);
        assert_eq!(
            got.len(),
            want.data.len(),
            "{}#{member}: element count mismatch (recorded shape {:?})",
            self.manifest.fixture,
            want.shape
        );
        let max_delta = got
            .iter()
            .zip(&want.data)
            .map(|(a, b)| (a - b).abs() as f64)
            .fold(0.0f64, f64::max);
        println!(
            "parity {}#{member}: max|delta| = {max_delta:.3e} (tolerance {:.3e})",
            self.manifest.fixture, self.manifest.tolerance
        );
        assert!(
            max_delta <= self.manifest.tolerance,
            "{}#{member}: max|delta| {max_delta:.6e} exceeds tolerance {:.6e}",
            self.manifest.fixture,
            self.manifest.tolerance
        );
    }
}

fn member_name(file_ref: &str) -> &str {
    file_ref.split('#').nth(1).expect("npz member after '#'")
}

fn tensor2_to_vec(t: Tensor<B, 2>) -> Vec<f32> {
    t.into_data().to_vec().expect("tensor to host")
}

fn tensor4_to_vec(t: Tensor<B, 4>) -> Vec<f32> {
    t.into_data().to_vec().expect("tensor to host")
}

fn model_manifest(name: &str) -> ModelManifest {
    let path = repo_root().join(format!("models/{name}.manifest.json"));
    let json =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&json).expect("model manifest parses")
}

// ---------------------------------------------------------------------------
// Per-model runners
// ---------------------------------------------------------------------------

fn run_detector(name: &str) {
    let Some(fixture) = load_fixture(name) else {
        return;
    };
    let detector = SsdSlim320::new(fixture.weights());
    let out = detector.forward(fixture.input()).expect("detector forward");
    let confidences: Vec<f32> = out.confidences.iter().flatten().copied().collect();
    let boxes: Vec<f32> = out
        .boxes
        .iter()
        .flat_map(|b| [b.x1, b.y1, b.x2, b.y2])
        .collect();
    fixture.check("confidences", &confidences);
    fixture.check("boxes", &boxes);
}

fn run_landmark(name: &str, config: MfnDwConfig, check_conv_features: bool) {
    let Some(fixture) = load_fixture(name) else {
        return;
    };
    let net = MobileFaceNetDw::new(fixture.weights(), config);
    let (landmarks, conv_features) = net.forward(fixture.input()).expect("landmark forward");
    fixture.check("landmarks", &tensor2_to_vec(landmarks));
    if check_conv_features {
        let flat: Vec<f32> = conv_features.into_data().to_vec().expect("tensor to host");
        fixture.check("conv_features", &flat);
    }
}

// ---------------------------------------------------------------------------
// Tests, one per fixture in tools/fixtures/INDEX.json
// ---------------------------------------------------------------------------

#[test]
fn parity_detector_real() {
    run_detector("detector-real");
}

#[test]
fn parity_detector_rand() {
    run_detector("detector-rand");
}

#[test]
fn parity_landmark64_rand() {
    run_landmark("landmark64-rand", MfnDwConfig::upstream_64(), false);
}

#[test]
fn parity_landmark_pipnet_real() {
    let Some(fixture) = load_fixture("landmark-pipnet-real") else {
        return;
    };
    let arch = match model_manifest("landmark-pipnet").arch {
        Arch::Pipnet(arch) => arch,
        other => panic!("unexpected arch: {other:?}"),
    };
    let net = PipnetLandmark::new(fixture.weights(), PipnetConfig::from_arch(&arch));
    let out = net.forward(fixture.input()).expect("pipnet forward");
    fixture.check("cls", &tensor4_to_vec(out.cls));
    fixture.check("x", &tensor4_to_vec(out.x));
    fixture.check("y", &tensor4_to_vec(out.y));
    fixture.check("nb_x", &tensor4_to_vec(out.nb_x));
    fixture.check("nb_y", &tensor4_to_vec(out.nb_y));
}

#[test]
fn parity_embedder_mfn_real() {
    let Some(fixture) = load_fixture("embedder-mfn-real") else {
        return;
    };
    let arch = match model_manifest("embedder-mfn").arch {
        Arch::MobileFaceNet(MfnArch::Bottleneck(arch)) => arch,
        other => panic!("unexpected arch: {other:?}"),
    };
    let net = MobileFaceNetEmbedder::new(fixture.weights(), MfnBottleneckConfig::from_arch(&arch));
    let embedding = net.forward(fixture.input()).expect("embedder forward");
    fixture.check("embedding", &tensor2_to_vec(embedding));
}

#[test]
fn parity_embedder_foamliu_real() {
    let Some(fixture) = load_fixture("embedder-foamliu-real") else {
        return;
    };
    let arch = match model_manifest("embedder-foamliu").arch {
        Arch::MobileFaceNet(MfnArch::InvertedResidualV2(arch)) => arch,
        other => panic!("unexpected arch: {other:?}"),
    };
    let net = MobileFaceNetV2Embedder::new(fixture.weights(), MfnV2Config::from_arch(&arch));
    let embedding = net.forward(fixture.input()).expect("embedder forward");
    fixture.check("embedding", &tensor2_to_vec(embedding));
}

#[test]
fn parity_irn50_rand() {
    let Some(fixture) = load_fixture("irn50-rand") else {
        return;
    };
    let net = Irn50::new(fixture.weights());
    let embedding = net.forward(fixture.input()).expect("irn50 forward");
    fixture.check("embedding", &tensor2_to_vec(embedding));
}

/// Guards against fixtures being added to INDEX.json without a matching
/// parity test above.
#[test]
fn index_fixtures_all_covered() {
    let index_path = fixtures_dir().join("INDEX.json");
    let Ok(json) = std::fs::read_to_string(&index_path) else {
        eprintln!("skipping: {} absent", index_path.display());
        return;
    };
    #[derive(serde::Deserialize)]
    struct Index {
        fixtures: Vec<IndexEntry>,
    }
    #[derive(serde::Deserialize)]
    struct IndexEntry {
        name: String,
    }
    let index: Index = serde_json::from_str(&json).expect("INDEX.json parses");
    let covered = [
        "detector-real",
        "detector-rand",
        "landmark64-rand",
        "landmark-pipnet-real",
        "irn50-rand",
        "embedder-mfn-real",
        "embedder-foamliu-real",
    ];
    for entry in &index.fixtures {
        assert!(
            covered.contains(&entry.name.as_str()),
            "fixture {} in INDEX.json has no parity test",
            entry.name
        );
    }
}
