/**
 * Weight + manifest fetching. Files are served from `/models/` — i.e.
 * `web/public/models/` (git-ignored), populated by `web/build-wasm.sh`
 * (which copies the converted safetensors + manifests from `models/`,
 * themselves produced by `python3 tools/fetch_and_convert.py`).
 *
 * Missing files are a hard error: the UI runs only the real engine, so
 * `loadWeights` throws with actionable instructions instead of degrading.
 */

import type { WeightBundle } from './engine';

export const WEIGHT_FILES = {
  detector: 'detector-slim320.safetensors',
  landmark: 'landmark-mfn68.safetensors',
  embedder: 'embedder-mfn.safetensors',
} as const;

export const MANIFEST_FILES = {
  landmark: 'landmark-mfn68.manifest.json',
  embedder: 'embedder-mfn.manifest.json',
} as const;

export interface WeightProgress {
  /** Which file. */
  name: string;
  /** Bytes received so far. */
  received: number;
  /** Total bytes, or null when the server sent no Content-Length. */
  total: number | null;
}

/** Fetch + validate one file; dev servers return index.html for misses. */
async function fetchRaw(url: string): Promise<Response> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  const type = res.headers.get('content-type') ?? '';
  if (type.includes('text/html')) throw new Error(`${url}: not found (got HTML)`);
  return res;
}

/** Streaming fetch of one binary file with progress callbacks. */
async function fetchWithProgress(
  url: string,
  name: string,
  onProgress?: (p: WeightProgress) => void,
): Promise<Uint8Array> {
  const res = await fetchRaw(url);

  const lenHeader = res.headers.get('content-length');
  const total = lenHeader ? parseInt(lenHeader, 10) : null;

  if (!res.body) {
    const buf = new Uint8Array(await res.arrayBuffer());
    onProgress?.({ name, received: buf.length, total: buf.length });
    return buf;
  }

  const reader = res.body.getReader();
  const chunks: Uint8Array[] = [];
  let received = 0;
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    chunks.push(value);
    received += value.length;
    onProgress?.({ name, received, total });
  }

  const out = new Uint8Array(received);
  let off = 0;
  for (const c of chunks) {
    out.set(c, off);
    off += c.length;
  }
  return out;
}

/**
 * Everything served from `/models/` except the two non-redistributable
 * networks: the redistributable detector (MIT lineage) plus the two arch
 * manifests (metadata generated by this repo). This is what the public
 * Pages demo ships; the landmark + embedder weights are supplied by the
 * user (drop-zone) because upstream publishes no LICENSE for them.
 */
export interface WeightBase {
  detector: Uint8Array;
  landmarkManifest: string;
  embedderManifest: string;
}

/** The landmark + embedder safetensors — fetched from `/models/` when present
 *  (local dev), otherwise supplied by the user through the drop-zone. */
export interface UserWeights {
  landmark: Uint8Array;
  embedder: Uint8Array;
}

/**
 * Outcome of an auto-load from `/models/`:
 *  - `complete`: all five files were present (local dev) — run immediately.
 *  - `partial`: only the redistributable base was present (Pages demo) —
 *    the UI collects the two remaining weights from the user.
 */
export type WeightLoadResult =
  | { kind: 'complete'; bundle: WeightBundle }
  | { kind: 'partial'; base: WeightBase; missing: string[] };

/** Combine the redistributable base with the two user-supplied weights. */
export function combineWeights(base: WeightBase, user: UserWeights): WeightBundle {
  return {
    detector: base.detector,
    landmark: user.landmark,
    embedder: user.embedder,
    landmarkManifest: base.landmarkManifest,
    embedderManifest: base.embedderManifest,
  };
}

/**
 * Cheap sanity check that a user-dropped file is really a safetensors blob
 * (8-byte little-endian header length, then a JSON header): catches dropping
 * the wrong file before it reaches the wasm loader's opaque error.
 */
export function assertSafetensors(bytes: Uint8Array, label: string): void {
  if (bytes.length < 9) throw new Error(`${label}: file too small to be safetensors`);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const headerLen = Number(view.getBigUint64(0, true));
  if (headerLen <= 0 || headerLen > bytes.length - 8) {
    throw new Error(`${label}: not a safetensors file (bad header length)`);
  }
  if (bytes[8] !== 0x7b /* '{' */) {
    throw new Error(`${label}: not a safetensors file (header is not JSON)`);
  }
}

/** Read a picked/dropped File into bytes and validate it as safetensors. */
export async function readSafetensorsFile(file: File, label: string): Promise<Uint8Array> {
  const bytes = new Uint8Array(await file.arrayBuffer());
  assertSafetensors(bytes, label);
  return bytes;
}

/** Fetch the redistributable base: detector safetensors + both manifests.
 *  These ship with the app; a miss here is a genuine deployment fault. */
async function loadBase(
  onProgress: ((p: WeightProgress) => void) | undefined,
  baseUrl: string,
): Promise<WeightBase> {
  try {
    const [detector, landmarkManifest, embedderManifest] = await Promise.all([
      fetchWithProgress(baseUrl + WEIGHT_FILES.detector, 'detector', onProgress),
      fetchRaw(baseUrl + MANIFEST_FILES.landmark).then((r) => r.text()),
      fetchRaw(baseUrl + MANIFEST_FILES.embedder).then((r) => r.text()),
    ]);
    return { detector, landmarkManifest, embedderManifest };
  } catch (err) {
    throw new Error(
      `redistributable model base missing from /models/ ` +
        `(${err instanceof Error ? err.message : err}). ` +
        'Fix: python3 tools/fetch_and_convert.py, then ./web/build-wasm.sh ' +
        '(it copies the detector + manifests into web/public/models/).',
    );
  }
}

/** Try to fetch one optional weight; returns null when it is simply absent. */
async function tryFetchWeight(
  url: string,
  name: string,
  onProgress?: (p: WeightProgress) => void,
): Promise<Uint8Array | null> {
  try {
    return await fetchWithProgress(url, name, onProgress);
  } catch {
    return null; // absent on the public demo — collected from the user instead
  }
}

/**
 * Auto-load weights from `/models/`. The redistributable base (detector +
 * manifests) is required. The landmark + embedder weights are loaded when
 * present (local dev); when absent (Pages demo) a `partial` result is
 * returned and the two files are collected from the user.
 *
 * Throws only when the base itself is unreachable (a broken deployment).
 */
export async function loadWeights(
  onProgress?: (p: WeightProgress) => void,
  baseUrl = 'models/',
): Promise<WeightLoadResult> {
  const base = await loadBase(onProgress, baseUrl);
  const [landmark, embedder] = await Promise.all([
    tryFetchWeight(baseUrl + WEIGHT_FILES.landmark, 'landmark', onProgress),
    tryFetchWeight(baseUrl + WEIGHT_FILES.embedder, 'embedder', onProgress),
  ]);

  if (landmark && embedder) {
    return { kind: 'complete', bundle: combineWeights(base, { landmark, embedder }) };
  }
  const missing: string[] = [];
  if (!landmark) missing.push(WEIGHT_FILES.landmark);
  if (!embedder) missing.push(WEIGHT_FILES.embedder);
  return { kind: 'partial', base, missing };
}

export function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}
